### ISSUE TITLE
Add more drinks

### ISSUE THREAD

**Issue by XenGi** [coffeestats/coffeestats-django#42]
Lately there are more and more drinks finding it's way into the community. I can't count how many different mate variants there are at the moment but I also think that a general Mate entry is enough for them.
Drinks I would like to be added separately from mate and coffee are coke/cola (i.e. premium cola and fritz cola is very common in hackerspaces).
So what about adding cola to the list of drinks?

**Comment by jandd** [comment]
I like the idea and the database schema allows this quite easily. What I am missing currently is an idea how to properly allow input/data display for more than very few drink types. I have colleagues that requested to add green tea or caffeinated energy drinks too.

**Comment by XenGi** [comment]
Energy drinks sound like a new drink type because they are basically all the same. Tea is different enough from coffee to also be another drink type.
I think with these 2 also added we should have everybody covered.

We would have 5 drinks in total then. Still sounds like few enough to use the same gui like now. Maybe the layout of the statistics page could be changed to a tabbed view with one tab for every drink and a summary tab with all combined. so that there are not so many charts on one page.

The onthego page just could just add 3 more buttons like the rest of the places where drinks are listed or can be chosen.

I could help with the django stuff. I possibly have some free time in the next weeks. Just point me to the right directions and I will try out a few things.
